/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package garagem;

/**
 *
 * @author Neal
 */
public class Garagem extends javax.swing.JFrame {

    /**
     * Creates new form Garagem
     */
    public Garagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E1BE = new javax.swing.JButton();
        E1BF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        E2BA = new javax.swing.JButton();
        E2BB = new javax.swing.JButton();
        E2BC = new javax.swing.JButton();
        E2BD = new javax.swing.JButton();
        E2BE = new javax.swing.JButton();
        E2BF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        E3BA = new javax.swing.JButton();
        E3BB = new javax.swing.JButton();
        E3BC = new javax.swing.JButton();
        E3BD = new javax.swing.JButton();
        E3BE = new javax.swing.JButton();
        E3BF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        E4BA = new javax.swing.JButton();
        E4BB = new javax.swing.JButton();
        E4BC = new javax.swing.JButton();
        E4BD = new javax.swing.JButton();
        E4BE = new javax.swing.JButton();
        E4BF = new javax.swing.JButton();
        E1BA = new javax.swing.JButton();
        E1BB = new javax.swing.JButton();
        E1BC = new javax.swing.JButton();
        E1BD = new javax.swing.JButton();
        E5BE = new javax.swing.JButton();
        E5BF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        E5BA = new javax.swing.JButton();
        E6BA = new javax.swing.JButton();
        E5BB = new javax.swing.JButton();
        E6BB = new javax.swing.JButton();
        E5BC = new javax.swing.JButton();
        E6BC = new javax.swing.JButton();
        E5BD = new javax.swing.JButton();
        E6BD = new javax.swing.JButton();
        E6BE = new javax.swing.JButton();
        E6BF = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adicionarBtn = new javax.swing.JButton();
        retirarBtn = new javax.swing.JButton();
        procurarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        E1BE.setText("1 BLOCO E");

        E1BF.setText("1 BLOCO F");

        jLabel1.setText("ESTANTE 1");

        E2BA.setText("2 BLOCO A");
        E2BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2BAActionPerformed(evt);
            }
        });

        E2BB.setText("2 BLOCO B");

        E2BC.setText("2 BLOCO C");

        E2BD.setText("2 BLOCO D");

        E2BE.setText("2 BLOCO E");

        E2BF.setText("2 BLOCO F");

        jLabel2.setText("ESTANTE 2");

        jLabel3.setText("ESTANTE 3");

        E3BA.setText("3 BLOCO A");

        E3BB.setText("3 BLOCO B");
        E3BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3BBActionPerformed(evt);
            }
        });

        E3BC.setText("3 BLOCO C");

        E3BD.setText("3 BLOCO D");

        E3BE.setText("3 BLOCO E");

        E3BF.setText("3 BLOCO F");

        jLabel4.setText("ESTANTE 4");

        E4BA.setText("4 BLOCO A");

        E4BB.setText("4 BLOCO B");

        E4BC.setText("4 BLOCO C");

        E4BD.setText("4 BLOCO D");

        E4BE.setText("4 BLOCO E");

        E4BF.setText("4 BLOCO F");

        E1BA.setText("1 BLOCO A");
        E1BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1BAActionPerformed(evt);
            }
        });

        E1BB.setText("1 BLOCO B");
        E1BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1BBActionPerformed(evt);
            }
        });

        E1BC.setText("1 BLOCO C");
        E1BC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1BCActionPerformed(evt);
            }
        });

        E1BD.setText("1 BLOCO D");
        E1BD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1BDActionPerformed(evt);
            }
        });

        E5BE.setText("5 BLOCO E");

        E5BF.setText("5 BLOCO F");

        jLabel5.setText("ESTANTE 5");

        E5BA.setText("5 BLOCO A");
        E5BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5BAActionPerformed(evt);
            }
        });

        E6BA.setText("6 BLOCO A");
        E6BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6BAActionPerformed(evt);
            }
        });

        E5BB.setText("5 BLOCO B");
        E5BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5BBActionPerformed(evt);
            }
        });

        E6BB.setText("6 BLOCO B");

        E5BC.setText("5 BLOCO C");
        E5BC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5BCActionPerformed(evt);
            }
        });

        E6BC.setText("6 BLOCO C");

        E5BD.setText("5 BLOCO D");
        E5BD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5BDActionPerformed(evt);
            }
        });

        E6BD.setText("6 BLOCO D");

        E6BE.setText("6 BLOCO E");

        E6BF.setText("6 BLOCO F");

        jLabel6.setText("ESTANTE 6");

        adicionarBtn.setText("ADICIONAR");

        retirarBtn.setText("RETIRAR");

        procurarBtn.setText("PROCURAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retirarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procurarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel1)
                                    .addComponent(E1BE)
                                    .addComponent(E1BF)
                                    .addComponent(E1BC))
                                .addComponent(E1BA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(E1BB, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(E1BD, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(E2BA)
                            .addComponent(E2BB)
                            .addComponent(E2BC)
                            .addComponent(E2BD)
                            .addComponent(E2BE)
                            .addComponent(E2BF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(E3BA)
                            .addComponent(E3BB)
                            .addComponent(E3BC)
                            .addComponent(E3BD)
                            .addComponent(E3BE)
                            .addComponent(E3BF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(E4BA)
                            .addComponent(E4BB)
                            .addComponent(E4BC)
                            .addComponent(E4BD)
                            .addComponent(E4BE)
                            .addComponent(E4BF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel5)
                                    .addComponent(E5BE)
                                    .addComponent(E5BF)
                                    .addComponent(E5BC))
                                .addComponent(E5BA, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(E5BB, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(E5BD, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(E6BA)
                            .addComponent(E6BB)
                            .addComponent(E6BC)
                            .addComponent(E6BD)
                            .addComponent(E6BE)
                            .addComponent(E6BF))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarBtn)
                    .addComponent(retirarBtn)
                    .addComponent(procurarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E6BA)
                            .addComponent(E5BA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E6BB)
                            .addComponent(E5BB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E6BC)
                            .addComponent(E5BC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E6BD)
                            .addComponent(E5BD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E5BE)
                            .addComponent(E6BE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E5BF)
                            .addComponent(E6BF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E4BF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E3BF))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E2BA)
                            .addComponent(E1BA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E2BB)
                            .addComponent(E1BB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E2BC)
                            .addComponent(E1BC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E2BD)
                            .addComponent(E1BD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E1BE)
                            .addComponent(E2BE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E1BF)
                            .addComponent(E2BF))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E2BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2BAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E2BAActionPerformed

    private void E1BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1BAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1BAActionPerformed

    private void E1BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1BBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1BBActionPerformed

    private void E1BCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1BCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1BCActionPerformed

    private void E1BDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1BDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1BDActionPerformed

    private void E3BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3BBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E3BBActionPerformed

    private void E5BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5BAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E5BAActionPerformed

    private void E6BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6BAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E6BAActionPerformed

    private void E5BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5BBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E5BBActionPerformed

    private void E5BCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5BCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E5BCActionPerformed

    private void E5BDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5BDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E5BDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Garagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Garagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Garagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Garagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Garagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E1BA;
    private javax.swing.JButton E1BB;
    private javax.swing.JButton E1BC;
    private javax.swing.JButton E1BD;
    private javax.swing.JButton E1BE;
    private javax.swing.JButton E1BF;
    private javax.swing.JButton E2BA;
    private javax.swing.JButton E2BB;
    private javax.swing.JButton E2BC;
    private javax.swing.JButton E2BD;
    private javax.swing.JButton E2BE;
    private javax.swing.JButton E2BF;
    private javax.swing.JButton E3BA;
    private javax.swing.JButton E3BB;
    private javax.swing.JButton E3BC;
    private javax.swing.JButton E3BD;
    private javax.swing.JButton E3BE;
    private javax.swing.JButton E3BF;
    private javax.swing.JButton E4BA;
    private javax.swing.JButton E4BB;
    private javax.swing.JButton E4BC;
    private javax.swing.JButton E4BD;
    private javax.swing.JButton E4BE;
    private javax.swing.JButton E4BF;
    private javax.swing.JButton E5BA;
    private javax.swing.JButton E5BB;
    private javax.swing.JButton E5BC;
    private javax.swing.JButton E5BD;
    private javax.swing.JButton E5BE;
    private javax.swing.JButton E5BF;
    private javax.swing.JButton E6BA;
    private javax.swing.JButton E6BB;
    private javax.swing.JButton E6BC;
    private javax.swing.JButton E6BD;
    private javax.swing.JButton E6BE;
    private javax.swing.JButton E6BF;
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton procurarBtn;
    private javax.swing.JButton retirarBtn;
    // End of variables declaration//GEN-END:variables
}
